@startuml
'https://plantuml.com/class-diagram

class App {

    start()
    main()
}

class SaveFile {

Path defaultPath = userRoot
Path filePath = userInput

loadFile() - sets filePath
saveFile() - save to filePath


}

class TodoList {
String nameOfList
ArrayList<Todo> todoList

setTitle()
getTitle()

addTodo()
delTodo()

}

class Todo {

Date dueDate
String todoText
Boolean completed

setTodoText()
setDueDate()
setCompletedTrue()
setCompletedFalse()

getDueDate()
getTodoText()
getCompleted()


}





@enduml